import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import { Link, NavLink, Navigate, Route, Routes, useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";

import { api, ApiError, CredentialProfile, Job, ProxyProfile, User } from "./api";
import { crawlerById, crawlerCatalog, CrawlerDefinition, CrawlerId } from "./catalog";

type Session = { token: string; user: User };
const sessionKey = "crawler-api-session";

function loadSession(): Session | null {
  try { return JSON.parse(sessionStorage.getItem(sessionKey) || "null") as Session | null; } catch { return null; }
}

function languageOf(language: string) { return language === "en-US" ? "en" : "zh"; }
function friendlyError(error: unknown) { return error instanceof ApiError ? error.code : "REQUEST_FAILED"; }
function pretty(value: unknown) { return JSON.stringify(value, null, 2); }

function Brand() { return <Link className="brand" to="/"><span className="brand-mark">Y</span><span>Yunxi <em>API</em></span></Link>; }

function Shell({ session, setSession, children }: { session: Session | null; setSession: (value: Session | null) => void; children: ReactNode }) {
  const { i18n, t } = useTranslation();
  const toggle = () => i18n.changeLanguage(i18n.language === "zh-CN" ? "en-US" : "zh-CN");
  return <><header className="topbar"><Brand /><nav className="nav-links"><NavLink to="/">{t("nav.products")}</NavLink><NavLink to="/docs">{t("nav.docs")}</NavLink>{session && <><NavLink to="/console">{t("nav.console")}</NavLink><NavLink to="/profiles">{t("nav.profiles")}</NavLink></>}</nav><div className="nav-actions"><button className="language" onClick={toggle}>{t("common.language")}</button>{session ? <button className="text-button" onClick={() => { sessionStorage.removeItem(sessionKey); setSession(null); }}>{t("common.logout")}</button> : <><Link className="text-link" to="/login">{t("nav.login")}</Link><Link className="button small" to="/register">{t("nav.register")}</Link></>}</div></header>{children}</>;
}

function PlatformIcon({ crawler }: { crawler: CrawlerDefinition }) { return <span className={`platform-icon ${crawler.platform}`}>{crawler.icon}</span>; }

function Landing() {
  const { i18n, t } = useTranslation(); const locale = languageOf(i18n.language);
  return <main><section className="hero-section"><div className="hero-copy"><p className="eyebrow"><span />{t("hero.eyebrow")}</p><h1>{t("hero.title")}</h1><p className="lead">{t("hero.description")}</p><div className="hero-actions"><Link className="button" to="/console">{t("hero.primary")} <span>→</span></Link><Link className="button ghost" to="/docs">{t("hero.secondary")}</Link></div><p className="trust-line">{t("landing.trust")}</p></div><div className="orbital-card" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="core-glow" /><div className="api-pulse"><span className="pulse-dot" /> API / v1 <strong>200</strong></div>{crawlerCatalog.slice(0, 3).map((crawler, index) => <div key={crawler.id} className={`floating-platform platform-${index}`}><PlatformIcon crawler={crawler} /><small>{crawler[locale].name}</small></div>)}</div></section><section className="section"><div className="section-heading"><p className="eyebrow">CAPABILITIES</p><h2>{t("landing.supported")}</h2><p>{t("landing.supportedText")}</p></div><div className="crawler-grid">{crawlerCatalog.map((crawler) => <article className="crawler-card" key={crawler.id}><div className="crawler-card-top"><PlatformIcon crawler={crawler} /><code>{crawler.id}</code></div><h3>{crawler[locale].name}</h3><p>{crawler[locale].description}</p><Link to={`/console?crawler=${crawler.id}`}>{locale === "zh" ? "调用接口" : "Use API"} <span>→</span></Link></article>)}</div></section><section className="section steps-section"><div className="section-heading"><p className="eyebrow">QUICK START</p><h2>{t("landing.usage")}</h2></div><div className="steps"><div><b>01</b><h3>{t("landing.step1")}</h3></div><div><b>02</b><h3>{t("landing.step2")}</h3></div><div><b>03</b><h3>{t("landing.step3")}</h3></div></div></section><section className="section api-callout"><div><p className="eyebrow">API-FIRST</p><h2>{t("landing.apiFirst")}</h2><p>{t("landing.apiFirstText")}</p><Link className="button dark" to="/docs">{t("nav.docs")}</Link></div><pre>{`POST /api/v1/crawls/tmall.sku-adjust\nAuthorization: Bearer <token>\n\n{ "input": { "sku_id": "6277426546603" } }\n\n202 { "id": 42, "status": "queued" }`}</pre></section></main>;
}

function AuthPage({ mode, setSession }: { mode: "login" | "register"; setSession: (value: Session) => void }) {
  const { t } = useTranslation(); const navigate = useNavigate(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { const registered = mode === "register" ? await api.register(email, password) : null; const login = await api.login(email, password); const user: User = registered || { id: 0, email, trial_successes_remaining: 5, is_formal: false }; const session = { token: login.access_token, user }; sessionStorage.setItem(sessionKey, JSON.stringify(session)); setSession(session); navigate("/console"); } catch (err) { setError(friendlyError(err)); } finally { setBusy(false); } };
  return <main className="auth-page"><section className="auth-card"><p className="eyebrow">YUNXI API</p><h1>{t(mode === "login" ? "auth.loginTitle" : "auth.registerTitle")}</h1><p>{mode === "register" && t("auth.trial")}</p><form onSubmit={submit}><label>{t("auth.email")}<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="name@example.com" /></label><label>{t("auth.password")}<input type="password" required minLength={10} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="至少 10 位" /></label>{error && <p className="form-error">{error}</p>}<button className="button wide" disabled={busy}>{busy ? t("common.loading") : t(mode === "login" ? "auth.login" : "auth.register")}</button></form><p className="auth-switch">{t(mode === "login" ? "auth.noAccount" : "auth.haveAccount")} <Link to={mode === "login" ? "/register" : "/login"}>{t(mode === "login" ? "auth.register" : "auth.login")}</Link></p></section></main>;
}

function RequireSession({ session, children }: { session: Session | null; children: ReactNode }) { return session ? <>{children}</> : <Navigate to="/login" replace />; }

function useProfiles(session: Session | null) {
  const [credentials, setCredentials] = useState<CredentialProfile[]>([]); const [proxies, setProxies] = useState<ProxyProfile[]>([]);
  const refresh = async () => { if (!session) return; const [savedCredentials, savedProxies] = await Promise.all([api.credentials(session.token), api.proxies(session.token)]); setCredentials(savedCredentials); setProxies(savedProxies); };
  useEffect(() => { void refresh(); }, [session?.token]);
  return { credentials, proxies, refresh };
}

function ConsolePage({ session }: { session: Session }) {
  const { i18n, t } = useTranslation(); const locale = languageOf(i18n.language); const { credentials, proxies } = useProfiles(session); const [selected, setSelected] = useState<CrawlerId>("tmall.sku-adjust"); const [input, setInput] = useState(pretty(crawlerById(selected)!.example)); const [credentialId, setCredentialId] = useState<number | undefined>(); const [proxyId, setProxyId] = useState<number | undefined>(); const [job, setJob] = useState<Job | null>(null); const [result, setResult] = useState<unknown>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const crawler = crawlerById(selected)!;
  const changeCrawler = (id: CrawlerId) => { setSelected(id); setInput(pretty(crawlerById(id)!.example)); setJob(null); setResult(null); setError(""); };
  useEffect(() => { if (!job || job.status === "succeeded" || job.status === "failed") return; const timer = window.setTimeout(async () => { try { const next = await api.job(session.token, job.id); setJob(next); if (next.status === "succeeded") setResult((await api.result(session.token, next.id)).result); } catch (err) { setError(friendlyError(err)); } }, 1500); return () => window.clearTimeout(timer); }, [job, session.token]);
  const submit = async () => { setError(""); setBusy(true); setResult(null); try { const parsed = JSON.parse(input); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error("INVALID_JSON"); const created = await api.submit(session.token, selected, { input: parsed, credential_profile_id: credentialId, proxy_profile_id: proxyId }); setJob(created); } catch (err) { setError(err instanceof SyntaxError || (err as Error).message === "INVALID_JSON" ? t("playground.invalidJson") : friendlyError(err)); } finally { setBusy(false); } };
  const currentCredentials = credentials.filter((profile) => profile.platform === crawler.platform);
  return <main className="console-page"><section className="console-intro"><div><p className="eyebrow">CONSOLE</p><h1>{t("dashboard.greeting")}</h1><p>{t("playground.description")}</p></div><div className="quota-card"><span>{session.user.is_formal ? t("dashboard.formal") : t("dashboard.trial")}</span><strong>{session.user.is_formal ? "∞" : session.user.trial_successes_remaining}</strong><small>{t("dashboard.remaining")}</small></div></section><section className="playground-layout"><aside className="api-list"><h2>{t("playground.choose")}</h2>{crawlerCatalog.map((item) => <button className={item.id === selected ? "api-option active" : "api-option"} onClick={() => changeCrawler(item.id)} key={item.id}><PlatformIcon crawler={item} /><span><b>{item[locale].name}</b><small>{item.id}</small></span></button>)}</aside><section className="request-panel"><div className="panel-head"><div><span className="method">POST</span><code>/api/v1/crawls/{selected}</code></div><p>{crawler[locale].description}</p></div><label>{t("playground.input")}<textarea value={input} onChange={(event) => setInput(event.target.value)} spellCheck={false} /></label><div className="select-row"><label>{t("playground.credential")}<select value={credentialId ?? ""} onChange={(event) => setCredentialId(event.target.value ? Number(event.target.value) : undefined)}><option value="">{t("playground.none")}</option>{currentCredentials.map((profile) => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label><label>{t("playground.proxy")}<select value={proxyId ?? ""} onChange={(event) => setProxyId(event.target.value ? Number(event.target.value) : undefined)}><option value="">{t("playground.none")}</option>{proxies.map((profile) => <option key={profile.id} value={profile.id}>{profile.name} · {profile.protocol}</option>)}</select></label></div>{crawler.credentialRequired && currentCredentials.length === 0 && <p className="inline-note">此接口需要 {crawler.platform} Cookie 配置档。请先到“凭据与代理”创建。</p>}{error && <p className="form-error">{error}</p>}<button className="button" disabled={busy || (crawler.credentialRequired && !credentialId)} onClick={submit}>{busy ? t("common.loading") : t("common.submit")} <span>→</span></button></section><section className="result-panel"><div className="panel-head"><h2>{t("playground.result")}</h2>{job && <span className={`status ${job.status}`}>{t(`playground.${job.status}`)}</span>}</div>{!job ? <div className="empty-state"><span>⌘</span><p>{t("dashboard.noJobs")}</p></div> : <><dl className="job-meta"><div><dt>ID</dt><dd>#{job.id}</dd></div><div><dt>Status</dt><dd>{job.status}</dd></div></dl>{job.error_code && <p className="form-error">{job.error_code}</p>}{result ? <pre>{pretty(result)}</pre> : <p className="pending-copy">{job.status === "queued" || job.status === "running" ? t("common.loading") : job.error_message}</p>}</>}</section></section></main>;
}

function ProfilesPage({ session }: { session: Session }) {
  const { t } = useTranslation(); const { credentials, proxies, refresh } = useProfiles(session); const [cookie, setCookie] = useState(""); const [credential, setCredential] = useState({ name: "", platform: "tmall", purpose: "" }); const [proxy, setProxy] = useState({ name: "", protocol: "http", host: "", port: "", username: "", password: "" }); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const saveCredential = async (event: FormEvent) => { event.preventDefault(); setError(""); try { await api.createCredential(session.token, { ...credential, cookie }); setCookie(""); setCredential({ name: "", platform: "tmall", purpose: "" }); setMessage(t("common.success")); await refresh(); } catch (err) { setError(friendlyError(err)); } };
  const saveProxy = async (event: FormEvent) => { event.preventDefault(); setError(""); try { await api.createProxy(session.token, { ...proxy, port: Number(proxy.port) }); setProxy({ name: "", protocol: "http", host: "", port: "", username: "", password: "" }); setMessage(t("common.success")); await refresh(); } catch (err) { setError(friendlyError(err)); } };
  return <main className="profiles-page"><section className="page-heading"><p className="eyebrow">SECURITY</p><h1>{t("profiles.title")}</h1><p>{t("profiles.description")}</p></section>{(message || error) && <p className={error ? "form-error" : "form-success"}>{error || message}</p>}<div className="profiles-grid"><section className="profile-block"><div className="block-head"><h2>{t("profiles.credential")}</h2><span>{credentials.length}</span></div><form className="profile-form" onSubmit={saveCredential}><label>{t("profiles.name")}<input required value={credential.name} onChange={(event) => setCredential({ ...credential, name: event.target.value })} /></label><label>{t("profiles.platform")}<select value={credential.platform} onChange={(event) => setCredential({ ...credential, platform: event.target.value })}><option value="taobao">淘宝</option><option value="tmall">天猫</option><option value="jd">京东</option></select></label><label className="full">{t("profiles.purpose")}<input value={credential.purpose} onChange={(event) => setCredential({ ...credential, purpose: event.target.value })} /></label><label className="full">{t("profiles.cookie")}<textarea required value={cookie} onChange={(event) => setCookie(event.target.value)} placeholder="key=value; key2=value2" /></label><button className="button">{t("profiles.createCredential")}</button></form><ProfileList empty={t("profiles.emptyCredentials")} rows={credentials.map((item) => <><b>{item.name}</b><small>{item.platform} · {item.purpose || "-"}</small></>)} /></section><section className="profile-block"><div className="block-head"><h2>{t("profiles.proxy")}</h2><span>{proxies.length}</span></div><form className="profile-form" onSubmit={saveProxy}><label>{t("profiles.name")}<input required value={proxy.name} onChange={(event) => setProxy({ ...proxy, name: event.target.value })} /></label><label>{t("profiles.protocol")}<select value={proxy.protocol} onChange={(event) => setProxy({ ...proxy, protocol: event.target.value })}><option value="http">HTTP</option><option value="https">HTTPS</option><option value="socks5">SOCKS5</option></select></label><label>{t("profiles.host")}<input required value={proxy.host} onChange={(event) => setProxy({ ...proxy, host: event.target.value })} /></label><label>{t("profiles.port")}<input required type="number" value={proxy.port} onChange={(event) => setProxy({ ...proxy, port: event.target.value })} /></label><label>{t("profiles.username")}<input value={proxy.username} onChange={(event) => setProxy({ ...proxy, username: event.target.value })} /></label><label>{t("profiles.proxyPassword")}<input type="password" value={proxy.password} onChange={(event) => setProxy({ ...proxy, password: event.target.value })} /></label><button className="button">{t("profiles.createProxy")}</button></form><ProfileList empty={t("profiles.emptyProxies")} rows={proxies.map((item) => <><b>{item.name}</b><small>{item.protocol}://{item.host}:{item.port}</small></>)} /></section></div></main>;
}

function ProfileList({ rows, empty }: { rows: ReactNode[]; empty: string }) { return <div className="saved-profiles">{rows.length ? rows.map((row, index) => <div className="saved-profile" key={index}>{row}</div>) : <p>{empty}</p>}</div>; }

function DocsPage() { const { i18n, t } = useTranslation(); const locale = languageOf(i18n.language); return <main className="docs-page"><section className="page-heading"><p className="eyebrow">REFERENCE</p><h1>{t("docs.title")}</h1><p>{t("docs.subtitle")}</p></section><div className="docs-layout"><aside><a href="#auth">{t("docs.authentication")}</a><a href="#flow">{t("docs.submit")}</a>{crawlerCatalog.map((crawler) => <a href={`#${crawler.id}`} key={crawler.id}>{crawler[locale].name}</a>)}</aside><article><section id="auth"><h2>{t("docs.authentication")}</h2><p>{t("docs.authenticationText")}</p><pre>{`Authorization: Bearer <access_token>`}</pre></section><section id="flow"><h2>{t("docs.submit")}</h2><pre>{`POST /api/v1/crawls/{crawler}\nContent-Type: application/json\n\n{\n  "input": { ... },\n  "credential_profile_id": 1,\n  "proxy_profile_id": 2\n}\n\n202 Accepted\n{ "id": 42, "crawler": "tmall.sku-adjust", "status": "queued" }`}</pre><h2>{t("docs.poll")}</h2><pre>{`GET /api/v1/jobs/42\nGET /api/v1/jobs/42/result`}</pre></section>{crawlerCatalog.map((crawler) => <section id={crawler.id} key={crawler.id}><div className="docs-api-title"><PlatformIcon crawler={crawler} /><div><h2>{crawler[locale].name}</h2><code>POST /api/v1/crawls/{crawler.id}</code></div></div><p>{crawler[locale].description}</p><h3>{t("docs.examples")}</h3><pre>{pretty({ input: crawler.example, ...(crawler.credentialRequired ? { credential_profile_id: 1 } : {}) })}</pre></section>)}<section><h2>{t("docs.errors")}</h2><table><tbody><tr><td>401</td><td>AUTH_REQUIRED / INVALID_TOKEN</td></tr><tr><td>403</td><td>TRIAL_QUOTA_EXHAUSTED</td></tr><tr><td>429</td><td>RATE_LIMITED</td></tr><tr><td>409</td><td>JOB_NOT_COMPLETE</td></tr></tbody></table></section></article></div></main>; }

export default function App() { const [session, setSession] = useState<Session | null>(loadSession()); return <Shell session={session} setSession={setSession}><Routes><Route path="/" element={<Landing />} /><Route path="/docs" element={<DocsPage />} /><Route path="/login" element={<AuthPage mode="login" setSession={setSession} />} /><Route path="/register" element={<AuthPage mode="register" setSession={setSession} />} /><Route path="/console" element={<RequireSession session={session}><ConsolePage session={session!} /></RequireSession>} /><Route path="/profiles" element={<RequireSession session={session}><ProfilesPage session={session!} /></RequireSession>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></Shell>; }
